version: '3'

services:
  agnos-httpd:
    image: agnos-apache:2.4
    ports:
      - "8080:80"
    network_mode: bridge
    volumes:
      - /home/parisek/Desktop/agnos/Products/Agnos/Program/public_html:/usr/local/apache2/htdocs/
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

#  agnos-molap-server:
#    image: agnos-molap-server:3.1
#    ports:
#      - "7979:7979"
#    network_mode: bridge
#    volumes:
#      - /home/agnos/Products/:/usr/local/agnos/Products/
#    logging:
#        driver: "json-file"
#        options:
#            max-file: "5"
#            max-size: "10m"

  agnos-report-server:
    image: agnos-report-server:2.0
#    ports:
#      - "9091:9091"
    network_mode: host
    volumes:
      - /home/parisek/Desktop/agnos/Products/:/usr/local/agnos/Products/
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"